server:
  port: 8082

spring:
  application:
    name: society-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/society_db}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_d4Z1MlrEazfX}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:society-ledger-super-secret-key-must-be-at-least-256-bits-long-for-hs256}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.societyledger: INFO
    org.springframework.security: WARN
