server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_d4Z1MlrEazfX}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@societyledger.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:society-ledger-super-secret-key-must-be-at-least-256-bits-long-for-hs256}
    access-token-expiry-ms: 900000    # 15 minutes
    refresh-token-expiry-ms: 604800000 # 7 days
  society-service:
    url: ${SOCIETY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.societyledger: INFO
    org.springframework.security: WARN
