server:
  port: 8085

spring:
  application:
    name: receipt-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/receipt_db}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_d4Z1MlrEazfX}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: receipt-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  jwt:
    secret: ${JWT_SECRET:society-ledger-super-secret-key-must-be-at-least-256-bits-long-for-hs256}
  society-service:
    url: ${SOCIETY_SERVICE_URL:http://localhost:8082}
  statement-service:
    url: ${STATEMENT_SERVICE_URL:http://localhost:8084}
  file-storage:
    base-path: ${FILE_STORAGE_PATH:${user.home}/society-ledger}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.societyledger: INFO
